import {
  CollectionIcon as CollectionIconSolid,
  ArrowLeftIcon as ArrowLeftIconSolid,
  ArrowsExpandIcon as ArrowsExpandIconSolid,
  DuplicateIcon as DuplicateIconSolid,
  DeviceMobileIcon as DeviceMobileIconSolid,
  ClockIcon as ClockIconSolid,
} from '@heroicons/react/solid';
import {
  ArrowLeftIcon,
  ArrowDownIcon,
  ArrowUpIcon,
  ArrowRightIcon,
  ChevronRightIcon,
  ChevronLeftIcon,
  ArrowsExpandIcon,
  DuplicateIcon,
  CollectionIcon,
  BellIcon,
  BeakerIcon,
  EyeIcon,
  EyeOffIcon,
  PlusIcon,
  SearchIcon,
  PaperAirplaneIcon,
  RefreshIcon,
  XIcon, // ErrorIcon, CrossIcon
  ExclamationIcon,
  ClipboardListIcon,
  CheckIcon,
  ExternalLinkIcon,
  SwitchVerticalIcon,
  GlobeAltIcon,
  LockClosedIcon,
  LinkIcon,
  PencilIcon,
  ShieldCheckIcon,
  ShieldExclamationIcon,
  ClockIcon,
} from '@heroicons/react/outline';
import { SpinnerIcon, QuestionIcon } from './icons';

// https://heroicons.com/

const AppIcons = {
  CollectionIcon,
  CollectionIconSolid,
  ArrowLeftIcon,
  ArrowLeftIconSolid,
  ArrowRightIcon,
  ArrowsExpandIcon,
  ArrowsExpandIconSolid,
  DuplicateIcon,
  DuplicateIconSolid,
  ArrowDownIcon,
  ArrowUpIcon,
  BellIcon,
  BeakerIcon,
  EyeIcon,
  EyeOffIcon,
  DeviceMobileIconSolid,
  PlusIcon,
  SearchIcon,
  PaperAirplaneIcon,
  RefreshIcon,
  ChevronRightIcon,
  ChevronLeftIcon,
  XIcon,
  ExclamationIcon,
  ClipboardListIcon,
  CheckIcon,
  SpinnerIcon,
  ExternalLinkIcon,
  QuestionIcon,
  SwitchVerticalIcon,
  GlobeAltIcon,
  LockClosedIcon,
  LinkIcon,
  PencilIcon,
  ShieldExclamationIcon,
  ShieldCheckIcon,
  ClockIcon,
  ClockIconSolid,
};

export default AppIcons;
