import {
  CollectionIcon as CollectionIconSolid,
  ArrowLeftIcon as ArrowLeftIconSolid,
  ArrowsExpandIcon as ArrowsExpandIconSolid,
  DuplicateIcon as DuplicateIconSolid,
  DeviceMobileIcon as DeviceMobileIconSolid,
} from '@heroicons/react/solid';
import {
  ArrowLeftIcon,
  ArrowDownIcon,
  ArrowUpIcon,
  ArrowsExpandIcon,
  DuplicateIcon,
  CollectionIcon,
  BellIcon,
  BeakerIcon,
  EyeIcon,
  EyeOffIcon,
  PlusIcon,
  SearchIcon,
  PaperAirplaneIcon,
  RefreshIcon,
} from '@heroicons/react/outline';

export default {
  CollectionIcon,
  CollectionIconSolid,
  ArrowLeftIcon,
  ArrowLeftIconSolid,
  ArrowsExpandIcon,
  ArrowsExpandIconSolid,
  DuplicateIcon,
  DuplicateIconSolid,
  ArrowDownIcon,
  ArrowUpIcon,
  BellIcon,
  BeakerIcon,
  EyeIcon,
  EyeOffIcon,
  DeviceMobileIconSolid,
  PlusIcon,
  SearchIcon,
  PaperAirplaneIcon,
  RefreshIcon,
};
